---
title: "Global Warming"
author: "Group 2 - Homework 2"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show 
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)

Sys.setlocale("LC_TIME", "English")
```


```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
library(vroom)
```



# Climate change and temperature anomalies 


To define temperature anomalies we need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.

```{r weather_data, cache=TRUE,warnings= FALSE, message=FALSE}

weather <- 
  read_csv("https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv", 
           skip = 1, 
           na = "***")

```


For each month and year, the dataframe shows the deviation of temperature from the normal (expected). 


```{r tidyweather}

tidyweather <- weather %>% 
        select(Year:Dec) %>%
        pivot_longer(cols=2:13, names_to="Month", values_to="delta")

```


## Plotting Information


```{r scatter_plot}

tidyweather <- tidyweather %>%
  mutate(date = ymd(paste(as.character(Year), Month, "1")),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=Year, y = delta))+
  geom_point()+
  geom_smooth(color="red") +
  theme_bw() +
  labs (
    title = "Increasing weather anomalies",
    subtitle = "Monthly temperature deviations over time",
    x = "Year",
    y = "Temperature deviation from expectation"
  )

```

```{r facet_wrap}
ggplot(tidyweather, aes(x=Year, y = delta))+
  geom_point(size=1)+
  geom_smooth(color="red") +
  theme_bw() +
  facet_wrap(~month) +
  labs (title = "Weather Anomalies (Monthly focus)", subtitle = "Monthly temperature deviations over time",
    x = "Year",
    y = "Temperature deviation from expectation")


```

```{r intervals}

comparison <- tidyweather %>% 
  filter(Year>= 1881) %>%     #remove years prior to 1881
  #create new variable 'interval', and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ "1881-1920",
    Year %in% c(1921:1950) ~ "1921-1950",
    Year %in% c(1951:1980) ~ "1951-1980",
    Year %in% c(1981:2010) ~ "1981-2010",
    TRUE ~ "2011-present"
  ))

```

```{r density_plot}

ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = "Density Plot for Monthly Temperature Anomalies",
    y     = "Density", x = "Temperature deviation from expectation"        #changing y-axis label to sentence case
  )

```

Now, we might be interested in average annual anomalies.

```{r averaging,warnings= FALSE, message=FALSE}

#creating yearly averages
average_annual_anomaly <- tidyweather %>% 
  group_by(Year) %>%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth(method="loess") +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = "Average Yearly Anomaly",
      subtitle = "Average yearly temperature deviation from the normal",
    y     = "Average Annual Delta",
    x = "Year"
  )                         


```
